### ISSUE TITLE
Down sizing JPG's, results in noise artefacts

### ISSUE THREAD

**Issue by uniquelau** [JimBobSquarePants/ImageProcessor#244]
When down sizing images, black/grey gradients are noticeable distorted. This resulting in areas of 'noise' and reduced colour range.

The issue is really noticeable on black and white photography, much less so in colour photography.

The issue considerably more noticeable on Retina / High Pixel Density displays, and also 'professional' displays which are correctly calibrated for the black colour space. 

e.g. [Black Test Card to check display performance](http://www.prad.de/images/monitore/eizo_hd2442w/eizo_hd2442w_levels_schwarz.jpg)

**Examples**

[Source Image](http://www.dmbrepresents.com/media/4332/bkc-sept10-276.jpg)
[Resized Image to 500px] (http://www.dmbrepresents.com/media/4332/bkc-sept10-276.jpg?width=500)

I also tried removing excess energy in the black area of the image, as I though perhaps there was some sort of issue here, however this has no impact.

If the image is resized in Photoshop, the issue is not present, so I'm assuming it's related to how the image is resized inside ImageProcessor.

All the best! Laurence

**Comment by christopherbauer** [comment]
Hi Laurence,

Can you post the code you're using so we can reliably repro the issue?

**Comment by uniquelau** [comment]
Hi Christopher, 

The site is running:   

<package id="ImageProcessor" version="2.2.8.0" targetFramework="net45" />
<package id="ImageProcessor.Web" version="4.3.6.0" targetFramework="net45" />

This is just using the normal web API, using the query string width=500, which is appended to the URL above :-)

**Comment by JimBobSquarePants** [comment]
Hey Laurence mate, Can you update your running version of Web to the latest? 4.4.0 so that the base library is updated.

I've seen issues like that before with earlier versions due to a bit of wonky maths but it's fixed now.

Here's a resized example from the latest release.

![b](https://cloud.githubusercontent.com/assets/385879/10694278/f421d908-79e8-11e5-9a4a-bbc4eee40db0.jpg)


The issue is caused by incorrect translation during resizing with gamma correction.

**Comment by uniquelau** [comment]
Hi Jim,

I have updated to the latest version of ImageProcessor and ImageProcessor.Web.

The severity of the problem is greatly reduced, but I still see some issues with banding of the blacks. I have made an image, that shows:

1. Before (using old version of ImageProcessor)
2. After (using latest version)
3. Source (no processing)

http://content.screencast.com/users/uniquelau/folders/Jing/media/d66fdec4-7d01-4910-9895-71162a10ea47/00000414.png

Let me know if I can help in anyway :-) Many thanks! Laurence

**Comment by JimBobSquarePants** [comment]
I think that's  compromise that I have to make while attempting to do gamma correction against the `System.Drawing` setup. 

Most people won't notice but when dealing with lots of greyscale issues it could be a problem. Annoyingly I made it optional on the `ImageFactory` class but not for the web extension. I'll get that added to the configuration.

**Comment by alecrt** [comment]
I can confirm the issue using latest 4.4.0 ImageProcessor.Web

Example:
Original: http://acc.quickportal.it/media/1029/mind.jpg
Processed: http://acc.quickportal.it/media/1029/mind.jpg?width=1400&height=550

**Comment by JimBobSquarePants** [comment]
Thanks @alecrt I did some maths checking recently using my v3 branch and I can confirm is caused by rounding error when caching srgb to linear to srgb conversion results. I'm gonna have to remove caching and make gamma correction optional and off by default as it will be slow.

**Comment by alecrt** [comment]
Great, and thank you for all your job!

**Comment by JimBobSquarePants** [comment]
I've switched of the gamma switch by default for ImageProcessor.Web and made it optional via config. There's simple no way to accurately do a conversion and inverse that covers all scenarios when working with bytes.

For v3 I've created a new Color struct that is more suitable for these kinds of operations and works flawlessly. https://github.com/JimBobSquarePants/ImageProcessor/blob/V3/src/ImageProcessor/Colors/Color.cs

**Comment by alecrt** [comment]
Thank you! Any ETA for the release?

**Comment by JimBobSquarePants** [comment]
No worries... I'll release something at the beginning of next week. I want to Run comprehensive testing first.

**Comment by JimBobSquarePants** [comment]
Fixed in the new release available on Nuget.

**Comment by alecrt** [comment]
Great, downloading it now! Many thx!

**Comment by JimBobSquarePants** [comment]
No worries :smile:

**Comment by uniquelau** [comment]
Awesome! Just tried to ping you some beer money via your PayPal link on
your site, but it's giving a 500 error!

On 1 December 2015 at 10:59, James Jackson-South <notifications@github.com>
wrote:

> No worries [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JimBobSquarePants/ImageProcessor/issues/244#issuecomment-160934971>
> .
>



-- 
Laurence Gillian

VooDooDog
20a Brownlow Mews,
London, WC1N 2LA

+44 (0)7763 849 700
+44 (0)20 7387 2049

lau@voodoodog.com
www.voodoodog.com

**Comment by JimBobSquarePants** [comment]
Paypal you bastards!  

Don't worry about it. :smile:

**Comment by uniquelau** [comment]
Hi James,

To confirm should the latest version resolve this issue? 

I'm still seeing some issues, with quite a big shift in colours / highlights.

1. Original
http://www.dmbrepresents.com/media/4336/bkc-sept10-1823.jpg

2. No resize, but via ImageProcessor
http://www.dmbrepresents.com/media/4336/bkc-sept10-1823.jpg?mode=max

Are we better off holding out till v3? Cheers, and thank's for all your time on this :dancers: Lau

**Comment by JimBobSquarePants** [comment]
Hey Laurence, 

It took me a while to figure out what is going on here. I'd made all the required changes to turn off any gamma correction I was making. 

Within ImageProcessor I use an extension method to make a copy of the image to process. You can see that method [here](https://github.com/JimBobSquarePants/ImageProcessor/blob/ab01a422b2c8463ee7bbaa57fe158fe5bb89f321/src/ImageProcessor/Common/Extensions/ImageExtensions.cs#L35).

Within that method you will see that I convert the PixelFormat to `PixelFormat.Format32bppPArgb`. This ensures that interpolation doesn't bleed rgb values (fixing issues with masking) and is also much, much [faster](http://stackoverflow.com/a/13176765/427899)  

The following code will replicate the issue outside ImageProcessor.

    using (MemoryStream inStream = new MemoryStream(photoBytes))
    {
        using (Image img = Image.FromStream(inStream, true))
        {
            using (Bitmap copy = ((Bitmap)img).Clone(new Rectangle(0, 0, img.Width, img.Height), PixelFormat.Format32bppPArgb))
            {
                copy.Save(Path.GetFullPath(Path.Combine(outPath, fileInfo.Name)));
            }
        }
    }

I'm at a loss as to how to fix this in V2 as I can't not change the PixelFormat. 

The issue doesn't occur in V3, I can decode/encode and resize the image without shift this is with gamma correction and premultiplied colors so I've no idea what Microsoft are doing wrong.

As for waiting til V3.... At this point I'm not even sure there ever will be one. I'm getting no help (bar the efforts from Jeavon helping me master the build process) from Microsoft nor the community at large and there's simply no way I can do it all. I'm already suffering serious burn out.
