### ISSUE TITLE
ImageProcessor Azure problems

### ISSUE THREAD

**Issue by critot** [JimBobSquarePants/ImageProcessor#365]
Hi James, I've some problem, and I'm not able to make the plugin working...

My environment:
Azure, basic plane, .net framework 4.6, pipeline integrated, host: http://xyz.azurewebsites.net;
A Blob service, https://xyz.blob.core.windows.net, width a container /photos (access type = blob);
A Cdn, http://xyz.azureedge.net, linked to the above blob.

I've installed the latest ImageProcessor, ImageProcessor.Web,  ImageProcessor.Web.Config, ImageProcessor.WebPlugins.AzureBlobCache, and the configs files are:

web.config

```
 <sectionGroup name="imageProcessor">
      <section name="security" requirePermission="false" type="ImageProcessor.Web.Configuration.ImageSecuritySection, ImageProcessor.Web" />
      <section name="processing" requirePermission="false" type="ImageProcessor.Web.Configuration.ImageProcessingSection, ImageProcessor.Web" />
      <section name="caching" requirePermission="false" type="ImageProcessor.Web.Configuration.ImageCacheSection, ImageProcessor.Web" />
    </sectionGroup>

    <httpModules>
    <add name="ImageProcessorModule" type="ImageProcessor.Web.HttpModules.ImageProcessingModule, ImageProcessor.Web" />
    </httpModules>

    <modules>
    <add name="ImageProcessorModule" type="ImageProcessor.Web.HttpModules.ImageProcessingModule, ImageProcessor.Web" />
    </modules>

<imageProcessor>
    <security configSource="config\imageprocessor\security.config" />
    <caching configSource="config\imageprocessor\cache.config" />
    <processing configSource="config\imageprocessor\processing.config" />
  </imageProcessor>
```

cache.config

```
  <cache name="AzureBlobCache" type="ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache, ImageProcessor.Web.Plugins.AzureBlobCache" maxDays="365">
      <settings>
        <setting key="CachedStorageAccount" value="DefaultEndpointsProtocol=https;AccountName=myaccountname;AccountKey=myaccountkey" />
        <setting key="CachedBlobContainer" value="cache" />
        <setting key="UseCachedContainerInUrl" value="false" />
        <setting key="CachedCDNRoot" value="http://xyz.azureedge.net" />        
        <setting key="SourceStorageAccount" value="DefaultEndpointsProtocol=https;AccountName=myaccountname;AccountKey=myaccountkey" />
        <setting key="SourceBlobContainer" value="photos" />
        <setting key="StreamCachedImage" value="false" />
      </settings>
    </cache>
```

security.config

```
   <service name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
   <settings>
        <setting key="Container" value="photos"/>
        <setting key="MaxBytes" value="8194304"/>
        <setting key="Timeout" value="30000"/>
        <setting key="Host" value="http://xyz.azurewebsites.net"/>
      </settings>
    </service>
```

processing.config: not modified

My webapp upload some files via an handler in chunks, commit them with a PutBlockList, create a container inside '/photos' and put the blobs; 
the only thing that happens is the creation of the cache container..I do not receive any type of error; when I call the images with a querystring the original images are returned.
I've tried different settings, for example:

in cache.config:
<setting key="UseCachedContainerInUrl" value="true" />
CachedStorageAccount and SourceStorageAccount with the complete conn string of the blob

in security.config:
prefix set to the /photos blob

but nothing... any idea?

thank you

**Comment by JimBobSquarePants** [comment]
Hi there,

I have a couple of suggestions.

Could you try setting the `cache.config` to the following?

``` xml
<cache name="AzureBlobCache" type="ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache, ImageProcessor.Web.Plugins.AzureBlobCache" maxDays="365">
    <settings>
    <setting key="CachedStorageAccount" value="DefaultEndpointsProtocol=https;AccountName=myaccountname;AccountKey=myaccountkey" />
    <setting key="UseCachedContainerInUrl" value="true" /> <!-- True unless you set the path when setting the CDN -->
    <setting key="SourceStorageAccount" value=""/> <!-- Don't need this any more -->
    <setting key="SourceBlobContainer" value=""/> <!-- Don't need this any more -->
    <setting key="CachedCDNRoot" value="http://xyz.azureedge.net/" />   
    <setting key="StreamCachedImage" value="false"/>     
    </settings>
</cache>
```

And your `security.config` to the following?

``` xml
<!-- Comment out your local image service  -->
<service name="CloudImageService" prefix="photos/" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
<settings>
    <setting key="MaxBytes" value="8194304"/>
    <setting key="Timeout" value="30000"/>
    <setting key="Host" value="http://xyz.azurewebsites.net/photos/"/> <!-- Note path in url -->
    </settings>
</service>
```

Hopefully that should help you get everything working. If not, could you help me diagnose the problem by sharing a link to an image stored in your photos blob. Both the blob and CDN versions if you can.

Cheers

James

**Comment by critot** [comment]
I've tried with that settings but nothing...

for your diagnosis

https://spotlightphotos.blob.core.windows.net/photos/critot/e4309eeb-4df7-4cc8-ab11-aad153479082.jpg
https://cdn-spotlight-blob.azureedge.net/photos/critot/e4309eeb-4df7-4cc8-ab11-aad153479082.jpg

the cdn endpoint is configured for accepting query strings

thank you!

**Comment by JimBobSquarePants** [comment]
Ok coke,

From those I can see that we should be definitely be enabling the cached container url in the settings.

Sorry but I have to ask...

How are you requesting your images? 

Absolute Url
https://spotlightphotos.blob.core.windows.net/photos/critot/e4309eeb-4df7-4cc8-ab11-aad153479082.jpg

or 

Relative Url (The correct way)
/photos/critot/e4309eeb-4df7-4cc8-ab11-aad153479082.jpg

If you are using the relative url then could you try changing the `Host` value to

<setting key="Host" value="https://spotlightphotos.blob.core.windows.net/photos/"/>

The first value should be working though.

**Comment by critot** [comment]
After uploading to the blob simple create a client side <img> to show the image with absolute url plus querystring....but not sure if I understand the question..!

**Comment by JimBobSquarePants** [comment]
Image requests should be made with a relative url not an absolute one.

Think about it like this. The request you are making is outside of your current domain so it never hits the server. This means that ImageProcessor.Web can never intercept the call. 

When you are using the relative url ImageProcessor.Web will capture that request since it is pointing at the server where ImageProcessor.Web is installed. This will then make an external HttpRequest by combining the Host url + the relative url. 

Does that make sense?

**Comment by critot** [comment]
ok, the process is clear now, I've updated the url to relative, and

with the querystring I get error 500:

[KeyNotFoundException: The given key was not present in the dictionary.]
   System.Collections.Generic.Dictionary`2.get_Item(TKey key) +11770017
   ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache..ctor(String requestPath, String fullPath, String querystring) +70
   lambda_method(Closure , String , String , String ) +55
   ImageProcessor.Web.Extensions.InstanceCreationFactory`3.CreateInstanceOf(Type type, TArg1 arg1, TArg2 arg2, TArg3 arg3) +65
   ImageProcessor.Web.Extensions.TypeInitializationExtensions.GetInstance(Type type, TArg1 argument1, TArg2 argument2, TArg3 argument3) +59
   ImageProcessor.Web.HttpModules.<ProcessImageAsync>d__b.MoveNext() +2328
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar) +71
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +380
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

without query string : 404 not found

...

**Comment by JimBobSquarePants** [comment]
That looks to me like you are missing settings in your cache config. Can you confirm you have it set up like the instructions?

**Comment by critot** [comment]
Hi, certainly I'm making something wrong...

this is my cache config
```

  <cache name="AzureBlobCache" type="ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache, ImageProcessor.Web.Plugins.AzureBlobCache" maxDays="365">
      <settings>
        <setting key="CachedStorageAccount" value="DefaultEndpointsProtocol=https;AccountName=[myAccountName];AccountKey=[myAccountKey] />
        <setting key="UseCachedContainerInUrl" value="true" />        
        <setting key="CachedCDNRoot" value="http://xyz.azureedge.net" />        
        <setting key="SourceStorageAccount" value="" />
        <setting key="SourceBlobContainer" value="" />
        <setting key="StreamCachedImage" value="false" />
      </settings>
    </cache>
```

and this my security.config

```
    <service name="CloudImageService" prefix="photos/" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="8194304"/>
        <setting key="Timeout" value="30000"/>
        <setting key="Host" value="http://xyz.azurewebsites.net/photos/"/>
        <!-- Note path in url -->
      </settings>
    </service>
```

**Comment by critot** [comment]
Hi james, any idea to resolve the problem? it doesn't work...
now, I have a suspicion... my webapp on azure doesn't get the cache.config settings; how does the AzureBlobCache plugin get that settings?
it's possible that I must set <appSettings> section  with key-value (and in that case the plugin must use CloudConfigurationManager.GetSetting(xyz)) and not <settings> for make it work?
I believe that this issue deserves an analysis, thank you

**Comment by JimBobSquarePants** [comment]
Truth be told I'm not quite sure what has gone wrong and what you are doing.

There is no reason to be using CloudConfigurationManager at all. This plugin works straight out of the box. 

If you want to send me a zip file with your app I can have a look?

**Comment by azzlack** [comment]
I've recently encountered the same problem as described here. Everything was correctly set up, similar config to an earlier site that was working (same as [you posted earlier](https://github.com/JimBobSquarePants/ImageProcessor/issues/365#issuecomment-211820481)), etc.

My problem turned out to be related to the new Azure CDN from the new portal. CDNs created in the old portal worked just fine, while CDNs created in the new one failed with 504 every time.

**Comment by JimBobSquarePants** [comment]
@azzlack Interesting. I'm able to work with the classic and new setup no problem. I'm assuming you gave the CDN time to propagate and have tried toggling the UseCachedContainerInUrl setting?

**Comment by critot** [comment]
Hi James,
I've deployed on Azure a new AppWeb; it was created with Visual Studio 2013 template, simple an AzureCloudService with a standard WebRole and the latest Imageprocessor installed via Nuget, nothing more. 
cache.config and security.config the same that we discussed above; I've uploaded an image to my blob (the CDN is running long since with endpoint the blob), opened the browser and called the url:

http://mywebapp.azureedge.net/photos/image.jpg --> return 404
http://mywebapp.azureedge.net/photos/image.jpg?width=100 --> return 500 'The given key was not present in the dictionary.'

Now, still I think that the problem are the .config files settings that are no read by Azure....

then, to answer to this 'There is no reason to be using CloudConfigurationManager at all' 
please take a look at
http://blog.mattmcloughlin.com/how-to-use-the-cloudconfigurationmanager-to-automatically-switch-app-settings/

I think that CloudConfigurationManager is the best, simple and complete option to make this plugin works in differents enviroments.... (however it is used by others image processor plugins ;) )
Thank you.

**Comment by JimBobSquarePants** [comment]
Hi Critot,

Thank for that link. I normally use config transforms with my CI to ensure that the correct settings are applied, but I'll look into it.

 I still have absolutely no idea what you are doing differently to others using this plugin. It just works.

This image for example 

https://www.teachershealth.com.au/media/1131/userstory-trevor-tmb.jpg?anchor=center&mode=crop&width=470&height=355&quality=85 

is being redirected to the following CDN url on processing.

https://prod-teachershealth.azureedge.net/cache/6/a/5/c/2/6/6a5c26513e42d70bb2c4b43bb1dc586e65c721b3.jpg

It's doing everything it should.

That first link you shared. 

http://mywebapp.azureedge.net/photos/image.jpg 

Is that the actual url to the image? I'm guessing that is a CDN url but its obviously incorrect. 
That second url http://mywebapp.azureedge.net/photos/image.jpg?width=100 

is also incorrect, you don't request the resized image from the CDN, you request it from the site itself using the `CloudImageService` and your relative url.

**Comment by critot** [comment]
sorry James I've got you wrong links informations in latest post:

my webapp link is similar to this
http://mywebapp.**azurewebsites.net**

I've a blob where I upload images directly via azure portal, eg image.jpg inside 'photos' blob container with public rights

I've a cdn related and active to that blob
http://mywebapp-blob.**azureedge.net**

then
I call the image with this url: azure site link + blob container + image (is that wrong?)
http://mywebapp.azurewebsites.net/photos/images.jpg
...and get 404, no redirect to CDN url...

this is the first problem; then with querystring I get 500, but this is perhaps a related problem

**Comment by JimBobSquarePants** [comment]
>I call the image with this url: azure site link + blob container + image (is that wrong?)
http://mywebapp.azurewebsites.net/photos/images.jpg
 ...and get 404, no redirect to CDN url...

I'd like to test something here.
Can you use the following software to look into your blob storage account? You should be able to see your image and right-click on it to get the web url.

http://www.cloudberrylab.com/free-microsoft-azure-explorer.aspx

To fix your config issues I'm going to have to see a copy of your solution. Could you zip something up and send it to me?

You can always change your passwords after if you're concerned. My email is on this page. https://github.com/JimBobSquarePants

**Comment by critot** [comment]
the url of my blob is like:
https://mywebapp.blob.core.windows.net/photos/image.jpg

I sent you an email, thank you!

**Comment by JimBobSquarePants** [comment]
I kept an eye out for an email but I haven't seen one.

**Comment by critot** [comment]
I sent you on  james_south@hotmail.com...

**Comment by JimBobSquarePants** [comment]
Odd. I must have blocked you by accident when I was cleaning out my email. Sorry about that. 

Send it to jamesmsouth (at) gmail.com and it should go through.

**Comment by critot** [comment]
ok sended again at gmail, thank you

**Comment by JimBobSquarePants** [comment]
Excellent. I can see that. Will have a dig asap.

**Comment by JimBobSquarePants** [comment]
Hi @critot I've just spent the last wee while looking through that example project you sent me. I cannot find a single image request within the codebase. Without a more complete example I cannot really do much for you I'm afraid.

I did notice however that the default url given to me in the `CloudImageService` was inaccessible.

I get the following message.

>You do not have permission to view this directory or page.

**Comment by critot** [comment]
Hi James, thank you for your time, I owe you a beer...
for the default url, I forgot to enable default page in azure, now it works, so anyway...

I do not make requests in codebase; the sample app has imageprocessor installed and configured via .config files, then I make calls via browser; why a more complete example if this simple process dont work? for what I understand with ImageProcessor, ImageProcessor.Web, 
AzureBlobCache installed, the requests to [mywebsiteurl/myblobimage] should be intercepted and elaborated, is that correct? if yes why if I call ......[mywebsiteurl/myblobimage] I get 404?

_the process is the same that I've described some posts above:_
my webapp link is similar to this http://mywebapp.azurewebsites.net
I've a blob where I upload images directly via azure portal, eg image.jpg inside 'photos' blob container with public rights
I've a cdn related and active to that blob
http://mywebapp-blob.azureedge.net
I call the image with this url: azure site link + blob container + image (is that wrong?)
http://mywebapp.azurewebsites.net/photos/images.jpg
...and get 404, no redirect to CDN url...

times ago I've tried with another knowed plugin, same app and the required configurations in web.config, and the process runs without problems.

thank you

**Comment by critot** [comment]
Hi James, finally it works! 
the problem was the 'host' setting in my security.config... I didn't understand that it has to point to the blob storage and not the site url, this was not clear for me on the documentation!
Now, when I call an image with querystring in my app I get the image resized (with cdn link).

thank you.

**Comment by JimBobSquarePants** [comment]
Oh that's the best news! I'll update the documentation to make it more clear. :smile:

**Comment by chadcjc** [comment]
I too am having similiar trouble and I'm sure its just a configuration issue. 

Scenario:
I have a website hosted in Azure and want to use blob storage as the image store along with Image Processor to resize and cache the images.  I have setup an Image Server website, Azure Storage Account, and CDN (see below for Urls).

Azure Resources Info:
Image Server Url: http://insprieimageserver2.azureedge.net/
Blob Storage Url: http://inspireqastorage.blob.core.windows.net
CND End Point Url:  http://inspireqa2.azureedge.net/

Here are some images that are hosted in my blob storage 
http://inspireqastorage.blob.core.windows.net/images/system/6678c28f-4578-4593-9fa1-40eefda7047b.jpg
http://inspireqastorage.blob.core.windows.net/images/system/672e2692-860d-4785-a172-e5c03227f547.jpg
http://inspireqastorage.blob.core.windows.net/images/system/672e2692-860d-4785-a172-e5c03227f547.jpg

I would expect the following would serve up these images resized and pointing at the CDN but all I get is 404s
http://inspireimageserver2.azurewebsites.net/images/system/6678c28f-4578-4593-9fa1-40eefda7047b.jpg?width=100&height=100
http://inspireimageserver2.azurewebsites.net/images/system/672e2692-860d-4785-a172-e5c03227f547.jpg?width=100&height=100
http://inspireimageserver2.azurewebsites.net/images/system/672e2692-860d-4785-a172-e5c03227f547.jpg?width=100&height=100


I created a new web project installed the plug-ins and configured it as follows.  So far this is no code solution.

cache.config
<?xml version="1.0" encoding="utf-8"?>
<caching currentCache="AzureBlobCache">
  <caches>
    
    
    <cache name="AzureBlobCache" type="ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache, ImageProcessor.Web.Plugins.AzureBlobCache" maxDays="365">
      <settings>
        <setting key="CachedStorageAccount" value="DefaultEndpointsProtocol=https;AccountName=inspireqastorage;AccountKey=[Our Account Key]" />
        
        <setting key="CachedBlobContainer" value="cache" />
        <setting key="UseCachedContainerInUrl" value="true" />
        
        <setting key="CachedCDNRoot" value="http://inspireqa2.azureedge.net/" />
        <setting key="CachedCDNTimeout" value="1000" />
        <setting key="SourceStorageAccount" value="" />
        <setting key="SourceBlobContainer" value="" />
        <setting key="StreamCachedImage" value="false" />
      </settings>
    </cache>
  </caches>
</caching>

security.config
<?xml version="1.0" encoding="utf-8"?>
<security>
  <services>
    
    
    <service name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        
        <setting key="Container" value="images"/>
        <setting key="MaxBytes" value="8194304"/>
        <setting key="Timeout" value="30000"/>
        
        <setting key="Host" value="http://inspireqastorage.blob.core.windows.net"/>
      </settings>
    </service>
    <service prefix="remote.axd" name="RemoteImageService" type="ImageProcessor.Web.Services.RemoteImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="4194304" />
        <setting key="Timeout" value="3000" />
        <setting key="Protocol" value="http" />
      </settings>
      <whitelist>
      </whitelist>
    </service>
  </services>
</security>

I have attached CDN Configurations:
![cdn2](https://cloud.githubusercontent.com/assets/1395173/25871568/d6f4cee0-34bc-11e7-866b-c227316d30de.png)
![cdn1](https://cloud.githubusercontent.com/assets/1395173/25871567/d6f412de-34bc-11e7-9887-3bd834684381.png)

Any help is appreciated.

Thanks,
Chad
