### ISSUE TITLE
Mono

### ISSUE THREAD

**Issue by JimBobSquarePants** [JimBobSquarePants/ImageProcessor#64]
Get this working.

Things broken just now:

- Animated gifs
- DllImport.

Fix these and we can :shipit:

**Comment by kodfodrasz** [comment]
The Mono gdi+ version has some limitations.

Sorry, Wall of text coming :person_frowning:, but IMHO this belongs here, not to a separate issue.

For the code
~~~ csharp
                    ISupportedImageFormat format = new JpegFormat { Quality = 70 };
                    Size size = new Size(500, 500);
                    using (var inStream = File.OpenRead(path)) {
                        Console.WriteLine("Processing file {0}...", path);

                        using (var outStream = File.OpenWrite(thumbnailPath)) {
                            // Initialize the ImageFactory using the overload to preserve EXIF metadata.
                            using (ImageFactory imageFactory = new ImageFactory(preserveExifData: false)) {
                                // Load, resize, set the format and quality and save an image.

                                var sw = new Stopwatch();
                                Console.Write("  generating thumb...");
                                sw.Start();
                                imageFactory.Load(inStream)
                                            .AutoRotate()
                                            .Constrain(size)
                                            .Format(format)
                                            .Save(outStream);
                                sw.Stop();
                                Console.WriteLine(" done! {0} ms", sw.ElapsedMilliseconds);
                                thumbnailTime += sw.Elapsed;
                            }
                            // Do something with the stream.
                        }
~~~

I get the following error:
~~~
1|ggergely@icarus:~/tmp/sandbox $ MONO_IOMAP=all mono sandbox.exe .                                                                         Processing file ./P8120772.JPG...
  generating thumb...
Unhandled Exception:
ImageProcessor.Common.Exceptions.ImageProcessingException: Error processing image with Gamma ---> System.ArgumentException: A null reference or invalid value was found [GDI+ status: InvalidParameter]
  at System.Drawing.GDIPlus.CheckStatus (Status status) [0x00000] in <filename unknown>:0
  at System.Drawing.Bitmap.SetResolution (Single xDpi, Single yDpi) [0x00000] in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) System.Drawing.Bitmap:SetResolution (single,single)
  at ImageProcessor.Processors.Gamma.ProcessImage (ImageProcessor.ImageFactory factory) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at ImageProcessor.Processors.Gamma.ProcessImage (ImageProcessor.ImageFactory factory) [0x00000] in <filename unknown>:0
  at ImageProcessor.Imaging.Formats.FormatBase.ApplyProcessor (System.Func`2 processor, ImageProcessor.ImageFactory factory) [0x00000] in <filename unknown>:0
  at ImageProcessor.Imaging.Formats.JpegFormat.ApplyProcessor (System.Func`2 processor, ImageProcessor.ImageFactory factory) [0x00000] in <filename unknown>:0
  at ImageProcessor.ImageFactory.Gamma (Single value) [0x00000] in <filename unknown>:0
  at ImageProcessor.ImageFactory.Load (System.IO.Stream stream) [0x00000] in <filename unknown>:0
  at sandbox.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: ImageProcessor.Common.Exceptions.ImageProcessingException: Error processing image with Gamma ---> System.ArgumentException: A null reference or invalid value was found [GDI+ status: InvalidParameter]
  at System.Drawing.GDIPlus.CheckStatus (Status status) [0x00000] in <filename unknown>:0
  at System.Drawing.Bitmap.SetResolution (Single xDpi, Single yDpi) [0x00000] in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) System.Drawing.Bitmap:SetResolution (single,single)
  at ImageProcessor.Processors.Gamma.ProcessImage (ImageProcessor.ImageFactory factory) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at ImageProcessor.Processors.Gamma.ProcessImage (ImageProcessor.ImageFactory factory) [0x00000] in <filename unknown>:0
  at ImageProcessor.Imaging.Formats.FormatBase.ApplyProcessor (System.Func`2 processor, ImageProcessor.ImageFactory factory) [0x00000] in <filename unknown>:0
  at ImageProcessor.Imaging.Formats.JpegFormat.ApplyProcessor (System.Func`2 processor, ImageProcessor.ImageFactory factory) [0x00000] in <filename unknown>:0
  at ImageProcessor.ImageFactory.Gamma (Single value) [0x00000] in <filename unknown>:0
  at ImageProcessor.ImageFactory.Load (System.IO.Stream stream) [0x00000] in <filename unknown>:0
  at sandbox.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
1|ggergely@icarus:~/tmp/sandbox $ mono --version
Mono JIT compiler version 4.0.1 (tarball Tue May 12 16:19:40 BST 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen
ggergely@icarus:~/tmp/sandbox $ rpm -ql libgdiplus0
/usr/lib64/libgdiplus.so
/usr/lib64/libgdiplus.so.0
/usr/lib64/libgdiplus.so.0.0.0
/usr/share/doc/libgdiplus0-3.12
/usr/share/doc/libgdiplus0-3.12/AUTHORS
/usr/share/doc/libgdiplus0-3.12/COPYING
/usr/share/doc/libgdiplus0-3.12/ChangeLog
/usr/share/doc/libgdiplus0-3.12/NEWS
/usr/share/doc/libgdiplus0-3.12/README
ggergely@icarus:~/tmp/sandbox $ rpm -qa libgdiplus0
libgdiplus0-3.12-1.x86_64
ggergely@icarus:~/tmp/sandbox $ uname -a
Linux icarus 3.10.0-229.4.2.el7.x86_64 #1 SMP Wed May 13 10:06:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
ggergely@icarus:~/tmp/sandbox $
~~~

Other details:
OS is centos 7, x64. Mono is installed from http://download.mono-project.com/repo/centos/ repository

**Comment by JimBobSquarePants** [comment]
Difficult to see exactly what is breaking and I don't have a machine to test on. It looks like it could be the gamma method which is handled differently in the latest build. Do you think you could build it and test?

**Comment by kodfodrasz** [comment]
Sure. Which branch should I check? Does building need anything else than checkout and pressing the build button in VS?

**Comment by kodfodrasz** [comment]
With a library compiled from 7afd05a I got the following error:
~~~
ggergely@icarus:~/tmp/sandbox $ MONO_IOMAP=all mono sandbox.exe .
Processing file ./P8120772.JPG...
  generating thumb...
Unhandled Exception:
System.ArgumentException: A null reference or invalid value was found [GDI+ status: InvalidParameter]
  at System.Drawing.GDIPlus.CheckStatus (Status status) [0x00000] in <filename unknown>:0
  at System.Drawing.Bitmap.SetResolution (Single xDpi, Single yDpi) [0x00000] in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) System.Drawing.Bitmap:SetResolution (single,single)
  at ImageProcessor.Common.Extensions.ImageExtensions.Copy (System.Drawing.Image source, PixelFormat format) [0x00000] in <filename unknown>:0
  at ImageProcessor.ImageFactory.Load (System.IO.Stream stream) [0x00000] in <filename unknown>:0
  at sandbox.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: A null reference or invalid value was found [GDI+ status: InvalidParameter]
  at System.Drawing.GDIPlus.CheckStatus (Status status) [0x00000] in <filename unknown>:0
  at System.Drawing.Bitmap.SetResolution (Single xDpi, Single yDpi) [0x00000] in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) System.Drawing.Bitmap:SetResolution (single,single)
  at ImageProcessor.Common.Extensions.ImageExtensions.Copy (System.Drawing.Image source, PixelFormat format) [0x00000] in <filename unknown>:0
  at ImageProcessor.ImageFactory.Load (System.IO.Stream stream) [0x00000] in <filename unknown>:0
  at sandbox.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
1|ggergely@icarus:~/tmp/sandbox $
~~~

**Comment by JimBobSquarePants** [comment]
This is odd.. Mono looks like it supports `SetResolution` 

https://github.com/mono/mono/blob/88d2b9da2a87b4e5c82abaea4e5110188d49601d/mcs/class/System.Drawing/System.Drawing/Bitmap.cs#L307

Maybe it needs to be built on a non windows machine? 

This is waaay outside my field of expertise now. I've only ever installed Ubuntu on a machine once (It lasted about half an hour as I couldn't get SublimeText plugins to work)

**Comment by kodfodrasz** [comment]
I'm digging around, and fount the following:

After adding the following debug printlines (debiugging on mono on a server is troublesome, at least for me) to `ImageExtensions.Copy()`: 
~~~ csharp
            Bitmap copy = ((Bitmap)source).Clone(new Rectangle(0, 0, source.Width, source.Height), format);

            System.Console.Error.WriteLine("DEBUG: copy: {0}", copy);
            System.Console.Error.WriteLine("DEBUG: format: {0}", format);
            System.Console.Error.WriteLine("DEBUG: xres: {0}; yres: {1}", source.HorizontalResolution, source.VerticalResolution);

            copy.SetResolution(source.HorizontalResolution, source.VerticalResolution);
~~~

I got the following output:
~~~
1|ggergely@icarus:~/tmp/sandbox $ MONO_IMAP=all mono ImageProcessor.PlayGround.exe Images/                                                  Processing file Images/00001.jpg...
  generating thumb...DEBUG: copy: System.Drawing.Bitmap
DEBUG: format: Format32bppPArgb
DEBUG: xres: 180; yres: 180
 done! 504 ms
Processing file Images/00002.jpg...
  generating thumb...DEBUG: copy: System.Drawing.Bitmap
DEBUG: format: Format32bppPArgb
DEBUG: xres: 0; yres: 0

Unhandled Exception:
System.ArgumentException: A null reference or invalid value was found [GDI+ status: InvalidParameter]
[... well known stack trace from above]
~~~

Which suggests that for some images the mono/libgdiplus duo mis-parses the images.
I can send an image to reproduce the error. I can totally view it on windows with no errors. More interresting is: I can `Bitmap.Load()` and `Bitmap.Save()` them on mono without an error...

**Comment by kodfodrasz** [comment]
This is clearly a mono bug. I have filed [mono bug 33310](https://bugzilla.xamarin.com/show_bug.cgi?id=33310) for the problem.

**Comment by JimBobSquarePants** [comment]
Thanks for looking into this. Yeah, definitely seems to be a bug there. Not sure what I can do about that as I need to ensure the ratio is the same throughout the pipeline.

`Bitmap.Load()` and `Bitmap.Save()` will most likely work since they do not attempt to adjust the pixel ratio.

**Comment by kodfodrasz** [comment]
I have tried to write a fallback of 96 dpi into `ImageExtensions.Clopy()`. On older versions without FastResizer it worked, but uncovered a different Mono bug: after resizing in the saved images the lower 20% of the image was somehow badly encoded, it was brighter. With FastResizer encoding of the images is also buggy on Mono: A black and white diffraction image pattern appears, with some features of the image recognizeable. I tried saving to Png and Jpeg, but the problem persisted. I'll investigate it further in the future, but currently i'm writing a fallback based on PInvoke and libgd to get the job done first.

**Comment by JimBobSquarePants** [comment]
I pushed a few updates earlier today which ironed out some issues I found with inconsistent pixel formats causing patterning on resize. That might solve some problems. 

All these issues make me want to start working on the [v3](https://github.com/JimBobSquarePants/ImageProcessor/tree/V3) branch again. I really think we were onto something there.

**Comment by kodfodrasz** [comment]
I have checked it on cbf468d but the problem persists on mono:
![00001 thumb](https://cloud.githubusercontent.com/assets/3705124/9434029/56b712b0-4a3a-11e5-822c-fae292b7cc75.jpg)

**Comment by JimBobSquarePants** [comment]
Wow that is odd! And it works fine on Windows? 

I still have the [old resize code](https://github.com/JimBobSquarePants/ImageProcessor/blob/acdde7a3a706dfe26ab5b8907a4429a0651f01b1/src/ImageProcessor/Imaging/Resizer.cs#L459) in the library so I could add a conditional for the mono solution to use that with the 96 dpi fallback.

**Comment by JimBobSquarePants** [comment]
I'm closing this as cross platform support will continue in V3
